#!/usr/bin/env python3

# run all of the tests

import os
import sys
from subprocess import run
from filecmp import cmp, dircmp

from libtest import get_srcrepobindirs

_, repo_path, bindirs = get_srcrepobindirs()

os.environ['PATH'] = os.pathsep.join([*os.environ['PATH'].split(os.pathsep), *bindirs])

run(["python", os.path.join(repo_path, "test", "tutorial.py")])

if os.name == "posix":
    run(os.path.join(repo_path, "test", "tutorial.sh"))

    def diff_tree(a, b):
        awalk = os.walk(a)
        bwalk = os.walk(b)
        different = False
        for arow,brow in zip(awalk, bwalk):
            afilt = list(filter(lambda x: not x.startswith("thresholds-dense"), arow[2]))
            bfilt = list(filter(lambda x: not x.startswith("thresholds-dense"), brow[2]))
            if afilt != bfilt:
                if "tfevents" in arow[2][0]:  continue
                print(afilt)
                print(bfilt)
                different = True
        return different

    if diff_tree(os.path.join(repo_path, "test", "scratch", "tutorial-sh"),
                 os.path.join(repo_path, "test", "scratch", "tutorial-py")):
        print("ERROR directory hierarchies differ between tutorial-{py,sh}")

    files = [os.path.join("groundtruth-data", "round1", "PS_20130625111709_ch3-detected.csv"),
             os.path.join("trained-classifier1", "train_1r", "thresholds.ckpt-30.csv"),
             os.path.join("trained-classifier1", "train_1r", "thresholds.ckpt-300.csv"),
             os.path.join("groundtruth-data", "round2", "20161207T102314_ch1-predicted-1.0pr.csv"),
             os.path.join("groundtruth-data", "round2", "20161207T102314_ch1-detected.csv"),
             os.path.join("groundtruth-data", "round2", "20161207T102314_ch1-missed.csv"),
             os.path.join("trained-classifier2", "train_1r", "thresholds.ckpt-30.csv"),
             os.path.join("trained-classifier2", "train_1r", "thresholds.ckpt-300.csv"),
             os.path.join("groundtruth-data", "round1", "PS_20130625111709_ch3-mistakes.csv"),
             os.path.join("omit-one", "generalize_1w", "thresholds.ckpt-30.csv"),
             os.path.join("omit-one", "generalize_1w", "thresholds.ckpt-300.csv"),
             os.path.join("nfeaturesexclusive-32", "xvalidate_1k", "thresholds.ckpt-30.csv"),
             os.path.join("nfeaturesexclusive-32", "xvalidate_1k", "thresholds.ckpt-300.csv"),
             os.path.join("nfeaturesexclusive-64", "xvalidate_1k", "thresholds.ckpt-30.csv"),
             os.path.join("nfeaturesexclusive-64", "xvalidate_1k", "thresholds.ckpt-300.csv"),
             os.path.join("groundtruth-data", "congruence.tic.ambient.csv"),
             os.path.join("groundtruth-data", "congruence.tic.mel-pulse.csv"),
             os.path.join("groundtruth-data", "congruence.tic.mel-sine.csv"),
             os.path.join("groundtruth-data", "congruence.label.ambient.csv"),
             os.path.join("groundtruth-data", "congruence.label.mel-pulse.csv"),
             os.path.join("groundtruth-data", "congruence.label.mel-sine.csv")
             ]
    for file in files:
      if not cmp(os.path.join(repo_path, "test", "scratch", "tutorial-sh", file),
                 os.path.join(repo_path, "test", "scratch", "tutorial-py", file),
                 shallow=False):
          print("WARNING "+file+" in tutorial-sh/ and tutorial-py/ differ")
          print("WARNING it is normal that the numbers therein are close but not exact")

run(["python", os.path.join(repo_path, "test", "seeds.py")])
run(["python", os.path.join(repo_path, "test", "freeze-classify.py")])
run(["python", os.path.join(repo_path, "test", "annotating.py")])
run(["python", os.path.join(repo_path, "test", "congruence.py")])
run(["python", os.path.join(repo_path, "test", "shiftby.py")])
run(["python", os.path.join(repo_path, "test", "visualization.py")])
