ARG UBUNTU_VERSION=20.04

FROM ubuntu:${UBUNTU_VERSION} as base

RUN apt-get update && apt-get install -y curl

# See http://bugs.python.org/issue19846
ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

RUN python3 -m pip --no-cache-dir install --upgrade \
    pip \
    setuptools

RUN ln -s $(which python3) /usr/local/bin/python

RUN python3 -m pip install --no-cache-dir tensorflow

#FROM tensorflow/tensorflow:latest

RUN apt-get update ; apt-get -y install wget zip

RUN cd /usr/lib/python3/dist-packages ; wget https://github.com/philipperemy/keras-tcn/archive/master.zip ; unzip master.zip ; rm master.zip ; cd keras-tcn-master ; pip3 install -r requirements.txt ; pip3 install . ; cd .. ; rm -rf keras-tcn-master

RUN cd /usr/lib/python3/dist-packages ; wget https://github.com/google-research/leaf-audio/archive/master.zip ; unzip master.zip ; rm master.zip ; cd leaf-audio-master ; sed -i /tensorflow-gpu/d requirements.txt ; pip3 install -e .

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get -y install vim python3-tk dc ssh libxml2 make tree python3-dev pkg-config

RUN pip3 install matplotlib scipy natsort scikit-image bokeh nitime sklearn umap-learn matplotlib_venn pandas av https://github.com/soft-matter/pims/archive/master.zip pyinterval dictdiffer psutil

RUN mkdir -p /usr/local/lib/nodejs ; wget https://nodejs.org/dist/v16.9.1/node-v16.9.1-linux-x64.tar.xz ; tar -xJvf node-v16.9.1-linux-x64.tar.xz -C /usr/local/lib/nodejs ; ln -s /usr/local/lib/nodejs/node-v16.9.1-linux-x64/bin/node /bin/node

COPY . /opt/songexplorer
ENV PATH="/opt/songexplorer/src:${PATH}" NUMBA_CACHE_DIR=/tmp/numba_cache MPLCONFIGDIR=/tmp/mpl_cache
CMD ["python"]
