#!/usr/bin/env python3

# delete unused checkpoints, to compact the size of models and conserve disk space.
# `ckpts-tokeep` is a comma-separated list of checkpoints to keep, one for each model
# in `logdir`.  if not supplied, all but the best checkpoint is deleted, as recorded
# in accuracy.log.

# delete-cktps <logdir> [ckpts-tokeep]

# e.g. delete-ckpts $PWD/trained-classifier 8750,10000,9500

import sys
import os
from glob import glob
import shutil
from natsort import natsorted
import ast
from datetime import datetime

import socket
from lib import *

srcdir, repodir, _ = get_srcrepobindirs()

print(str(datetime.now())+": start time")
with open(os.path.join(repodir, "VERSION.txt"), 'r') as fid:
  print('SongExplorer version = '+fid.read().strip().replace('\n',', '))
print("hostname = "+socket.gethostname())

if len(sys.argv)==3:
    _,logdir,ckpts_tokeep = sys.argv
    ckpts_tokeep = ckpts_tokeep.split(',')
    modeldirs = natsorted(filter(lambda x: os.path.isdir(os.path.join(logdir, x)) and
                                           not x.startswith("summaries"),
                                 os.listdir(logdir)))
else:
    _,logdir = sys.argv
    with open(os.path.join(logdir, "accuracy.log"), 'r') as fid:
        for line in fid:
            if line.startswith("models = "):
                modeldirs = ast.literal_eval(line[9:])
            if line.startswith("ckpts = "):
                ckpts_tokeep = ast.literal_eval(line[8:])

assert len(ckpts_tokeep) == len(modeldirs)

print('logdir: '+logdir)
print('ckpts_tokeep: '+str(ckpts_tokeep))
print('modeldirs: '+str(modeldirs))

def delete_glob(pattern, fn):
    for modeldir, ckpt_tokeep in zip(modeldirs, ckpts_tokeep):
        search_path = os.path.join(logdir, modeldir, pattern.replace('X', '*'))
        notpattern = pattern.replace('X', ckpt_tokeep).replace('*', '')
        for ckpt in glob(search_path):
            if notpattern not in ckpt:
                print('deleting '+ckpt)
                fn(ckpt)

delete_glob("ckpt-X.index", os.remove)
delete_glob("ckpt-X.data*", os.remove)
delete_glob("confusion-matrix.ckpt-X.pdf", os.remove)
delete_glob("logits.testing.ckpt-X.npz", os.remove)
delete_glob("logits.validation.ckpt-X.npz", os.remove)
delete_glob("precision-recall.ckpt-X.pdf", os.remove)
delete_glob("predictions.ckpt-X", shutil.rmtree)
delete_glob("probability-density.ckpt-X.pdf", os.remove)
delete_glob("specificity-sensitivity.ckpt-X.pdf", os.remove)
delete_glob("thresholds.ckpt-X.csv", os.remove)

print(str(datetime.now())+": finish time")
