#!/usr/bin/env python3

# train a neural network with the annotations

# train <context-ms> <shiftby-ms> <optimizer> <learning_rate> <audio-read-plugin> <audio-read-plugin-kwargs> <video-read-plugin> <video-read-plugin-kwargs> <video-findfile> <video-bkg-frames> <data-loader-queuesize> <data-loader-maxprocs> <model-architecture> <model-parameters-json> <logdir> <path-to-groundtruth> <label1>,<label2>,...,<labelN> <kinds-to-use> <nsteps> <restore-from> <save-and-validate-period> <validation-percentage> <mini-batch> <testing-files> <audio-tic-rate> <audio-nchannels> <video-frame-rate> <video-frame-width> <video-frame-height> <video-channels> <batch-seed> <weights-seed> <deterministic> <ireplicates>

# e.g.
# $SONGEXPLORER_BIN train 204.8 0.0 Adam 0.0002 load-wav '{}' load-avi-mp4-mov '{}' same-basename 1000 0 1 convolutional '{"representation":"waveform", "window_ms":6.4, "stride_ms":1.6, "mel_dct":"7,7", "dropout":0.5, "kernel_sizes":5,128", last_conv_width":130, "nfeatures":"256,256", "dilate_after_layer":65535, "stride_after_layer":65535, "connection_type":"plain"}' `pwd`/trained-classifier `pwd`/groundtruth-data mel-sine,mel-pulse,ambient,other annotated 50 '' 10 40 32 "" 5000 1 0 0 0 0 -1 -1 0 1,2,3,4

import os
import sys
from subprocess import run, PIPE, STDOUT
import asyncio

from datetime import datetime
import socket

print(str(datetime.now())+": start time")
repodir = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
with open(os.path.join(repodir, "VERSION.txt"), 'r') as fid:
  print('SongExplorer version = '+fid.read().strip().replace('\n',', '))
print("hostname = "+socket.gethostname())
print("CUDA_VISIBLE_DEVICES = "+os.environ.get('CUDA_VISIBLE_DEVICES',''))
p = run('which nvidia-smi && nvidia-smi', shell=True, stdout=PIPE, stderr=STDOUT)
print(p.stdout.decode('ascii').rstrip())

try:

  _, context_ms, shiftby_ms, optimizer, learning_rate, audio_read_plugin, audio_read_plugin_kwargs, video_read_plugin, video_read_plugin_kwargs, video_findfile, video_bkg_frames, data_loader_queuesize, data_loader_maxprocs, architecture, model_parameters, logdir, data_dir, labels_touse, kinds_touse, nsteps, restore_from, save_and_validate_period, validation_percentage, mini_batch, testing_files, audio_tic_rate, audio_nchannels, video_frame_rate, video_frame_width, video_frame_height, video_channels, batch_seed, weights_seed, deterministic, ireplicates = sys.argv[:35]

  print('context_ms: '+context_ms)
  print('shiftby_ms: '+shiftby_ms)
  print('optimizer: '+optimizer)
  print('learning_rate: '+learning_rate)
  print('audio_read_plugin: '+audio_read_plugin)
  print('audio_read_plugin_kwargs: '+audio_read_plugin_kwargs)
  print('video_read_plugin: '+video_read_plugin)
  print('video_read_plugin_kwargs: '+video_read_plugin_kwargs)
  print('video_findfile: '+video_findfile)
  print('video_bkg_frames: '+video_bkg_frames)
  print('data_loader_queuesize: '+data_loader_queuesize)
  print('data_loader_maxprocs: '+data_loader_maxprocs)
  print('architecture: '+architecture)
  print('model_parameters: '+model_parameters)
  print('logdir: '+logdir)
  print('data_dir: '+data_dir)
  print('labels_touse: '+labels_touse)
  print('kinds_touse: '+kinds_touse)
  print('nsteps: '+nsteps)
  print('restore_from: '+restore_from)
  print('save_and_validate_period: '+save_and_validate_period)
  print('validation_percentage: '+validation_percentage)
  print('mini_batch: '+mini_batch)
  print('testing_files: '+testing_files)
  print('audio_tic_rate: '+audio_tic_rate)
  print('audio_nchannels: '+audio_nchannels)
  print('video_frame_rate: '+video_frame_rate)
  print('video_frame_width: '+video_frame_width)
  print('video_frame_height: '+video_frame_height)
  print('video_channels: '+video_channels)
  print('batch_seed: '+batch_seed)
  print('weights_seed: '+weights_seed)
  print('deterministic: '+deterministic)
  print('ireplicates: '+ireplicates)

  save_fingerprints="False" if len(sys.argv)==35 else sys.argv[35]

  if restore_from:
    mode='a'
    start_checkpoint=os.path.join(logdir, "train_MODEL", "ckpt-"+restore_from)
  else:
    mode='w'
    start_checkpoint=''

  async def redirect(cmd):
    with open(cmd[-1], 'a') as fid:
      proc = await asyncio.create_subprocess_exec(*cmd[:-1],
                                                  stderr=asyncio.subprocess.PIPE,
                                                  stdout=fid)
      await proc.communicate()

  async def main():
    cmds = []
    for ireplicate in ireplicates.split(','):
      model=ireplicate+'r'
      expr=["loop",
            "--context_ms="+context_ms,
            "--shiftby_ms="+shiftby_ms,
            "--optimizer="+optimizer,
            "--learning_rate="+learning_rate,
            "--audio_read_plugin="+audio_read_plugin,
            "--audio_read_plugin_kwargs="+audio_read_plugin_kwargs,
            "--video_read_plugin="+video_read_plugin,
            "--video_read_plugin_kwargs="+video_read_plugin_kwargs,
            "--video_findfile="+video_findfile,
            "--video_bkg_frames="+video_bkg_frames,
            "--data_loader_queuesize="+data_loader_queuesize,
            "--data_loader_maxprocs="+data_loader_maxprocs,
            "--model_architecture="+architecture,
            "--model_parameters="+model_parameters,
            "--data_dir="+data_dir,
            "--labels_touse="+labels_touse,
            "--kinds_touse="+kinds_touse,
            "--how_many_training_steps="+nsteps,
            "--start_checkpoint="+start_checkpoint.replace("MODEL",model),
            "--save_step_period="+save_and_validate_period,
            "--validate_step_period="+save_and_validate_period,
            "--validation_percentage="+validation_percentage,
            "--validation_offset_percentage=0.0",
            "--batch_size="+mini_batch,
            "--testing_percentage=0.0",
            "--testing_files="+testing_files,
            "--audio_tic_rate="+audio_tic_rate,
            "--audio_nchannels="+audio_nchannels,
            "--video_frame_rate="+video_frame_rate,
            "--video_frame_width="+video_frame_width,
            "--video_frame_height="+video_frame_height,
            "--video_channels="+video_channels,
            "--random_seed_batch="+batch_seed,
            "--random_seed_weights="+weights_seed,
            "--deterministic="+deterministic,
            "--train_dir="+os.path.join(logdir,"train_"+model),
            "--summaries_dir="+os.path.join(logdir,"summaries_"+model),
            "--save_fingerprints="+save_fingerprints]

            #"--subsample_label=mel-pulse,mel-notpulse",
            #"--subsample_skip=4096",

            #"--partition_label=mel-pulse,mel-notpulse",
            #"--partition_n=4",
            #"--partition_training_files=PS_20130625111709_ch10.wav,PS_20130625111709_ch3.wav,PS_20130625155828_ch10.wav,PS_20130625155828_ch11.wav,PS_20130625155828_ch3.wav,PS_20130625155828_ch7.wav,PS_20130625155828_ch8.wav,PS_20130628144304_ch14.wav,PS_20130628144304_ch16.wav,PS_20130628144304_ch2.wav,PS_20130628144304_ch8.wav,PS_20130628165930_ch11.wav,PS_20130702114557_ch1.wav,PS_20130702114557_ch13.wav,PS_20130702114557_ch14.wav,PS_20130702144748_ch15.wav",
            #"--partition_validation_files=PS_20130625111709_ch7.wav,PS_20130625155828_ch6.wav,PS_20130628144304_ch15.wav,PS_20130702114557_ch10.wav",

      cmds.append(expr+[os.path.join(logdir,"train_"+model+".log")])
      with open(cmds[-1][-1], mode) as fid:
        fid.write(' '.join(cmds[-1][:-1])+'\n')

    await asyncio.gather(*[redirect(x) for x in cmds])

  asyncio.run(main())

except Exception as e:
  print(e)

finally:
  os.sync()
  print(str(datetime.now())+": finish time")
